import HeaderBar from "@/components/headerBar/HeaderBar";
import Navbar from "@/components/navbar/Navbar";
import NavPath from "@/components/subHeaderBar/NavPath";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/utils/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./_provider/AuthProvider";
import ColorThemeProvider from "./_provider/ColorThemeProvider";
import QueryProvider from "./_provider/QueryProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calendar-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="text-primary" lang="fr" suppressHydrationWarning>
      <body className={cn(inter.className, "bg-background overflow-y-hidden")}>
        <ColorThemeProvider>
          <AuthProvider>
            <QueryProvider>
              <div className="relative flex w-full">
                <Navbar />
                <div className="h-screen flex-1 overflow-y-scroll">
                  <div className="sticky top-0 z-50 w-full divide-y-2 divide-muted bg-background">
                    <HeaderBar />
                    <div className="pointer-events-none absolute inset-x-0 top-[50px] h-[24px] bg-gradient-to-b from-background to-transparent"></div>
                  </div>

                  <NavPath />
                  <div className="w-full p-2">{children}</div>
                </div>
              </div>
              <Toaster />
            </QueryProvider>
          </AuthProvider>
        </ColorThemeProvider>
      </body>
    </html>
  );
}
